### ISSUE TITLE
Getting edge attribute from rule chain

### ISSUE THREAD

**Issue by CalmNite** [thingsboard/thingsboard-edge#124]
Hello, 

I am using thingsboard-edge version 3.6 and i am having some problems retriving an attribute using the rule chain. 

First of all, i have several devices which have a relation with the edge entity. This images are from the main thingsboard.
![imagen](https://github.com/user-attachments/assets/925be206-68cc-41a5-973c-ec83171790fc)

This is the edge entity with the attribute i want.
![imagen](https://github.com/user-attachments/assets/963d5524-b9c6-4dcd-a58e-a58cb5a1186a)

When i try to change originator on the edge main rule chain. it doesnt find the element, how can i solve this problem.

![imagen](https://github.com/user-attachments/assets/85d3a473-9a2b-46e7-9494-46f14b17390d)

This is from the edge.
![imagen](https://github.com/user-attachments/assets/e1cd756b-b187-49e9-8949-b4ff91a208c3)

Thanks for the help!

**Comment by AndriiLandiak** [comment]
Hi, @CalmNite!

To send attributes update/delete events to Edge, you need to configure your rule chain on the TB side using the "push to edge" rule node (take a look at the screenshot)
![image](https://github.com/user-attachments/assets/06c6a526-44ee-4fe0-bd4e-79f65912326b)
![image](https://github.com/user-attachments/assets/69e8c7ce-ec3e-46c1-ad06-9b1cce1f8f1d)


Then, I'll modify the Edge Root Rule chain, using originator attributes with results in Metadata and log to verify the result:
![image](https://github.com/user-attachments/assets/18511aaf-f6c2-4052-ab44-7cd088d28c0c)
![image](https://github.com/user-attachments/assets/b06667de-803d-48a5-b249-a15fa71108a1)
![image](https://github.com/user-attachments/assets/c4611dcb-2b9f-46e3-b1d1-32de8d822691)

The problem was not sending attributes to Edge, with it you can implement your business logic! 

If you have questions related to this topic, feel free to reopen this PR or create a new one, if any new questions/issues occur.

**Comment by AndriiLandiak** [comment]
Also, we will provide a better approach in the next release to fetch the current edge attribute for its edge root rule chain, for example

**Comment by CalmNite** [comment]
Okey, I will try that solution. Thanks for the help!

**Comment by AndriiLandiak** [comment]
Hello, @CalmNite. I believe this could help you.

https://github.com/thingsboard/thingsboard-edge/pull/136
