### ISSUE TITLE
[Bug] JSON shared attributes are synced as String to the edge

### ISSUE THREAD

**Issue by thirstyfish** [thingsboard/thingsboard-edge#17]
**Describe the bug**
JSON type shared attributes are synced to the edge as String rather than JSON.

**Your Server Environment**
Own cloud instance running in k8s, v3.3.4.1 for both the TB cloud and the edge

**Your Client Environment**
Mac & Chrome

**To Reproduce**
1. Setup device in TB cloud with a JSON shared attribute and assign to a customer
2. Assign device to edge instance
3. Sync edge instance
4. Shared attribute is synced as String instead of JSON

**Expected behavior**
The type of the shared attribute should match the type of the attribute on the cloud

**Comment by volodymyr-babak** [comment]
Hello @thirstyfish,

I just tried it with the latest 3.4 release version and it works as expected.
Cloud:
![image](https://user-images.githubusercontent.com/3466101/180759283-319f6393-08a1-49f9-955e-facf88295e4c.png)
Edge:
![image](https://user-images.githubusercontent.com/3466101/180759323-da69f47d-91a4-4fc9-b3fe-c1d8e3571b20.png)

ThingsBoard 3.4 platform was released last week.
Edge 3.4 is going to be released tomorrow.
Please do upgrade to 3.4 once you'll have the possibility - the issue should be fixed.

**Comment by thirstyfish** [comment]
No worries, thanks @volodymyr-babak , we'll be testing with 3.4 in the near future.

**Comment by qiangwanfu** [comment]
边缘和云部署在一台服务器可以收到rpc 控制  部署在两台服务器上收不到rpc命令 什么原因呢3.4版本边和云都是

**Comment by qiangwanfu** [comment]
防火墙处于关闭状态 遥测数据可以同步

**Comment by thirstyfish** [comment]
Tested with 3.4 TB Edge and server versions and can confirm that the issue is resolved. Closing bug, thanks.

**Comment by AndreMaz** [comment]
@volodymyr-babak not sure why but this issue seems to be back in v3.5.1

Whenever I press "Sync Edge" the shared attributes @ TB-Cloud, that are specified as JSON, are synced to TB-Edge as String.

![image](https://github.com/thingsboard/thingsboard-edge/assets/9802754/e0819dbb-975c-4da7-953c-9aa41c21f0e7)

Temporary fix: After every "Sync Edge" I manually change type from String to JSON

**Comment by volodymyr-babak** [comment]
@AndreMaz 

The bug you mentioned is a separate issue but has been recently addressed in the following pull request: 
[GitHub PR #9091](https://github.com/thingsboard/thingsboard/pull/9091/files). 

This fix will be included in our upcoming release. Currently, we've frozen the addition of new features and are only accepting bug fixes. The new version is expected to be released in a couple of weeks.

**Comment by AndreMaz** [comment]
@volodymyr-babak thank you for quick response

*Totally unrelated to this issue* but is there any change that https://github.com/thingsboard/thingsboard-edge/issues/57#issuecomment-1704950106 issue is also addressed in the new release?

**Comment by aistisdev** [comment]
@volodymyr-babak 

Hello, I have encountered a similar problem with creating a String attribute, that gets converted to long after syncing between edge and tb:

![image](https://github.com/thingsboard/thingsboard-edge/assets/62371501/15fa6592-ee1b-409d-b5ac-fbc702d1c63a)
![image](https://github.com/thingsboard/thingsboard-edge/assets/62371501/8d22201c-2b5f-4422-ac83-e60e3ed8abbf)

This happens both ways (edge to tb, tb to edge) and only happens if I create String attribute that has only '0' symbols as shown in the screenshots.

I'm currently using thingsboard/tb-edge-pe:3.6.2EDGEPE and thingsboard/tb-pe-node:3.6.2PE. Has this been fixed in future newer versions?

**Comment by aistisdev** [comment]
> @aistisdev
> 
> to fix this behavior please add next parameter to conf files of thingsboard and edge services: `export JSON_TYPE_CAST_ENABLED=false`
> 
> In this way converters will not try to convert string values to integer if possible.

Thanks, seems to be working. Is there a specific reason that I should be aware of, as to why this option is set to true by default?

**Comment by volodymyr-babak** [comment]
@aistisdev 

I would say that historically this option was set to **true** by default.
We can't change default value for this parameter to **false** to avoid backward compatibility issues.
Considering number of issues related to this auto casting from String to Long, we probably considered to disable it at the start of the product, but for now we can't do this as a lot of deployment already working with this feature in place and disable it would broke a lot of production setups.
