### ISSUE TITLE
Connection between Edge and Thingsboard Docker Version

### ISSUE THREAD

**Issue by jose-franco-PT** [thingsboard/thingsboard-edge#45]
**Description**

Good morning,
I have successfully installed Thingsboard Edge on 4GB RAM Raspberry Pi 4 device through the installation instructions on Ubuntu operating system, as explained in the link below:

[https://thingsboard.io/docs/user-guide/install/edge/deb-installation/](url)

I then followed the instructions that are described in the following link:

[https://thingsboard.io/docs/edge/getting-started/](url)

Essentially, having followed the instructions described, I can now send data from Thingsboard Edge ( which is running inside the Raspberry Pi) to Thingsboard Cloud( [https://demo.thingsboard.io/login](url)).

Basically I created a python script that has an infinite loop sending dummy temperature values( from 0 to 100), via MQTT to thingsboard Edge. As you can see from the image below:

![1](https://user-images.githubusercontent.com/83010884/223997173-ee47e37a-8798-46e4-b85a-320d461dd4ea.png)

On the thingsboard Edge side the correct reception of the data is confirmed:
![2](https://user-images.githubusercontent.com/83010884/223997495-1b6a21a3-c5ea-423c-baa1-975c2a7ec966.png)

I then created a Dashboard according to the instructions in one of the links indicated above and successfully receive the information in Thingsboard Cloud:

![3](https://user-images.githubusercontent.com/83010884/223997924-af3cb971-6107-44e2-821f-51eb36e9214b.JPG)

Meanwhile I installed Thingsboard on Docker Windows 10, according to the instructions given in the following link:

[https://thingsboard.io/docs/user-guide/install/windows/](url)

At this moment, I have the following question:

Is it possible for Thingsboard Edge instead of sending data to Thingsboard Cloud, to send data to Thingsboard running on docker?

Thank you

**Environment**

 * OS:  Windows 10 64 bit
 * ThingsBoard: 3.4.4 (Docker Version)
 * Browser: name and version

**Comment by volodymyr-babak** [comment]
@jose-franco-PT 

yes, you can do this. 
First, you'll need to provision edge entity on your ThingsBoard that is running on docker following this guide:
https://thingsboard.io/docs/edge/provision-edge-on-server/

You did this already for ThingsBoard Cloud and now you should do the same for your ThingsBoard instance.

Once edge is provisioned on your ThingsBoard instance please follow installation guide again https://thingsboard.io/docs/user-guide/install/edge/deb-installation/. 
Probably you can skip 1, 2 and 3 steps because your edge is already installed and running fine.

But on the 4th step (https://thingsboard.io/docs/user-guide/install/edge/deb-installation/#step-4-configure-thingsboard-edge) you'll need properly set next variables:
![image](https://user-images.githubusercontent.com/3466101/224354320-f646f646-e19c-41f1-bc45-4af2cd7625ef.png)

So you'll need to update 4 variables above and in this way you should be able to connect to your ThingsBoard instance.

Here are more details what is **CLOUD_RPC_HOST**
![image](https://user-images.githubusercontent.com/3466101/224355114-8ef05313-3dcf-4287-8c4e-2018146b42e2.png)

**Comment by jose-franco-PT** [comment]
Good afternoon,

I just checked the instructions you sent me and it is already working.

Thank you very much for your attention!
