### ISSUE TITLE
[Question] Does edge support cluster deployment?

### ISSUE THREAD

**Issue by baigod** [thingsboard/thingsboard-edge#54]
Because I believe that GRPC is a single TCP, only one edge instance in the cluster can communicate with the thingsboard core. Does edge support cluster deployment?

![image](https://user-images.githubusercontent.com/23446974/235319598-5910b6b7-00d1-4e78-963d-ecbf66589ecd.png)

**Comment by volodymyr-babak** [comment]
Hello,

ThingsBoard Edge is not designed to run in a cluster deployment. The general concept is that you can connect multiple Edge instances to a ThingsBoard CE or PE server, based on your business requirements. However, these Edge instances will operate independently in a single mode rather than as part of a clustered setup.
