### ISSUE TITLE
[Question] Can Edge CE be connected to Thingsboard PE edition on the cloud?

### ISSUE THREAD

**Issue by cowherdboy** [thingsboard/thingsboard-edge#55]
Hello,

I have Thingsboard PE 3.4.3 running on cloud. I would like to know if it is possible to connect Edge CE to TB PE? I notice that the PE edition requests for Edge License Key.

Regards

**Comment by volodymyr-babak** [comment]
Hello,

ThingsBoard Edge Community Edition (CE) is designed to be compatible exclusively with the Community Edition of the ThingsBoard server. Unfortunately, it cannot be connected to the ThingsBoard Professional Edition (PE). This is due to differences in the gRPC object structures utilized for communication between ThingsBoard Edge and the ThingsBoard server in the CE and PE versions.
